### ISSUE TITLE
application.conf location

### ISSUE THREAD

**Issue by Ebsy** [red6/pdfcompare#29]
Hi there,

First off, I would like to thank the developers for this library. It's exactly what I'm looking for. I'm completely new to Java and I installed Eclipse/Maven for the first time yesterday just to get this library to run!

What I'm having an issue with is follows.
The docs specify an application.conf be created with additional parameters such as 'allowedDifferenceInPercentPerPage' and the file should be placed in the classes root. Due to my inexperience with Java, I'm having a hard time locating this classes root. I compile a .jar with Maven, is the classes root the same folder as the .jar?

Additionally, would it be possible to specify an application.conf at runtime? I have situations where various 'allowedDifference' thresholds are needed.

Thanks!

**Comment by finsterwalder** [comment]
The classpath is determined, when the application is started, so it very much depends on the way you start your application. The classpath can be given to the jvm upon startup as:
java -cp folder:jarfile:jarfile:folder:..... class.to.Start
You can put your application.conf in any directory, as long as it's listed in the classpath.
When you build an executable jar-file and start it with
java -jar yourjarfile.jar
it's a little different. Since then you can't provide an extra classpath. Then you have to either include everything inside the jar-file. Or you need to add other dependencies to the manifest.mf file inside the jar.
That should probably give you enough head start to further search for a solution?
With maven, everything in src/main/resources is included in jar and therefore in the classpath, when you execute it in Eclipse for example.

**Comment by Ebsy** [comment]
Great, thanks!
So I could potentially include the application.conf file in the mainfest.mf and make changes to the conf file before running the program?

**Comment by finsterwalder** [comment]
Probably yes. You need to try for yourself.
I don't know all the details from the top of my head eather.
Otherwise google for something like: java "-jar" manifest classpath
That should give you all the details.
