### ISSUE TITLE
Changing Java code to out requirement

### ISSUE THREAD

**Issue by smohannaidu** [red6/pdfcompare#45]
Hi,
Can you please let me know how to change java code of this library to our requirement. 

I have imported this maven library java class files. How can I change in my workspace. 

Can I extend these classes and use for custom requirement.

e.g. 1. Ignoring formatting changes
       2. Ignoring Green color fonts for pixels that are there where not expected

Regards
Mohan

**Comment by rmcdouga** [comment]
This is an open source project.  Can you not just fork the project and make whatever changes you wish to make?

**Comment by smohannaidu** [comment]
Can you please let us know how to change the Maven dependency class files used in this library.

e.g: Classes in the Maven Dependency package (de.redsix.pdfcompare) and (de.redsix.pdfcompare.ui)
PdfComparator.class
CompareResult
etc used in this library for our requirement change.

Regards
Mohan

**Comment by finsterwalder** [comment]
I don't really understand, what you want.
Are you familiar with Github and Open Source?
Are you familiar with Maven and Java software development?

If you want to change the existing code, you need to make a Fork on Github and change whatever you feel like in your own repository.
If it's a change/feature, that could be helpfull for others as well, please feel free to create a pull request.
If you want to make changes, that might be helpfull for others, it might make sense to discuss about your change first, so it will be easier to incorporate it later.

You can't really change class files, since the are compiled class files, not Java source code.
You can of course inherit from those class files in your code and use your own classes, where appropriate.

But that's normal Java development. I can't help you there.
