### ISSUE TITLE
Missing page not listed in `getDifferences`

### ISSUE THREAD

**Issue by FaustXVI** [red6/pdfcompare#69]
When comparing to PDF with a different number of pages, the missing pages are not present when calling `getDifferences` but are present in the PDF file obtained by using `write`.
Unfortunately I can't attach here the PDFs I use but I can send it to you by any mean you see fit if necessary.

Steps to reproduce : 
* Create two PDF, one with only one page (let's name it `onePage.pdf`), the second with two pages (`twoPages.pdf`)
* Programmatically compare them with `new PdfComparator<CompareResultImpl>("onePage.pdf","twoPages.pdf").compare()`
* Get the list of differences with `getDifferences()`

Current result : 
The list has one null element

Expected result :
The list has one PageArea element representing the whole missing page

By (very) quickly looking through the code (thus I am probably wrong), I think that in [`DiffImage#diffImages`](https://github.com/red6/pdfcompare/blob/e0b79bb7b43bfe9fae86d942c9a09677cae3843e/src/main/java/de/redsix/pdfcompare/DiffImage.java#L49) the `mark` function is call correctly but the `PageArea` is not created which makes it `null` as a result.

**Comment by finsterwalder** [comment]
Thanks for noticing this problem!
I fixed this in version 1.1.49 (to appear in maven central in a little while)

Your hunch about the problem was actually wrong. ;-)
Extra pages are handled differently in PdfComparator.addExtraPages(...) and there I created a PageDiffCalculator without a PageArea in the past, which was wrong.
